#ifndef __SERVERMANAGEMENT_H__
#define __SERVERMANAGEMENT_H__

#include "../ServerNetGen/serverNetGen.h"

typedef struct ChatServer ChatServer;

typedef enum ChatServer_Result
{
    SERVERMAN_SUCCESS = 0,
    SERVERMAN_INPUT_ERROR,
    SERVER_MAN_USER_NOT_REGISTERED,
    SERVER_MAN_GROUP_ALREADY_EXISTS,
    SERVER_MAN_GROUP_CREATE_FAILED,
    SERVERMAN_POINTER_NOT_INITIALIZED_ERROR,
    SERVERMAN_USER_REGISTER_FAIL,
    SERVERMAN_UNINITIALIZED_ERROR,
    SERVER_MAN_USER_ALREADY_REGISTERED,
    SERVER_MAN_USER_INSERT_FAILED,
    SERVERMAN_NOT_REGISTERED,
    SERVER_MAN_USER_ALREADY_LOGGED_IN,
    SERVER_MAN_USER_PASSWORD_INCORRECT,
    SERVER_MAN_GROUP_DOESNT_EXISTS,
    SERVER_MAN_USER_GROUP_NOT_FOUND,
    SERVER_MAN_GROUP_VECTOR_ERR,
    SERVER_MAN_USER_ADD_GROUP_ERR
} ChatServer_Result;

ChatServer *ChatServerCreate();

Server_Result RunChatServer(ChatServer *_chatServer);
void ChatServerDestroy(ChatServer** _chatServer);



#endif /* __SERVERMANAGEMENT_H__ */
