#ifndef __CLIENT_MANAGEMENT_H__
#define __CLIENT_MANAGEMENT_H__


typedef struct ClientMan ClientMan;

typedef enum ClientMan_Result 
{
	CLIET_MANAGE_SUCCESS,
	CLIET_MANAGE_CONNECT_ERROR,
	CLIET_MANAGE_UNINITIALIZED_ERROR,
	CLIET_MANAGE_ALLOCATION_ERROR,
	CLIET_MANAGE_REGISTRETION_ERROR,
	CLIET_MANAGE_LOGIN_ERROR,
	CLIET_MANAGE_SEND_ERROR,
	CLIET_MANAGE_RECIEVE_ERROR,
	CLINT_MAN_PROTOCOL_ERROR,
	CLIENT_MAN_INVALID_SELECTION,
	CLIENT_POINTER_NOT_INIT_ERR,
	CLIET_MANAGE_CREATE_GROUP_ERROR,
	CLIENT_MAN_VECTOR_CREATE_ERR,
	CLIENT_MAN_VECTOR_SIZE_ERR
}ClientMan_Result;


ClientMan* ClientManageCreate();
void ClientManDestroy(ClientMan** _clientMan);
ClientMan_Result Client_Run(ClientMan *_client);


#endif /* __CLIENT_MANAGEMENT_H__ */
